import os
import base64
from datetime import datetime

HTML_TEMPLATE = """
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>AStats Analysis Report</title>
    <style>
        :root {
            --primary: #2c3e50;
            --bg: #f8f9fa;
            --card-bg: #ffffff;
            --border: #e9ecef;
            --text: #333333;
            --accent: #3498db;
        }
        body {
            font-family: -apple-system, BlinkMacSystemFont, "Segoe UI", Roboto, Helvetica, Arial, sans-serif;
            line-height: 1.6;
            color: var(--text);
            background-color: var(--bg);
            margin: 0;
            padding: 2rem;
        }
        .container {
            max-width: 900px;
            margin: 0 auto;
            background: var(--card-bg);
            padding: 3rem;
            border-radius: 12px;
            box-shadow: 0 4px 6px rgba(0,0,0,0.05);
        }
        h1, h2, h3 { color: var(--primary); }
        .header {
            border-bottom: 2px solid var(--border);
            padding-bottom: 1rem;
            margin-bottom: 2rem;
        }
        .meta-info {
            color: #6c757d;
            font-size: 0.9em;
            display: flex;
            justify-content: space-between;
        }
        .query-box {
            background-color: #f1f8ff;
            border-left: 4px solid var(--accent);
            padding: 1rem 1.5rem;
            margin: 2rem 0;
            border-radius: 0 8px 8px 0;
        }
        .query-box h3 { margin-top: 0; color: var(--accent); }
        pre {
            background-color: #f4f4f4;
            padding: 1rem;
            border-radius: 6px;
            overflow-x: auto;
            font-size: 0.9em;
            border: 1px solid var(--border);
        }
        .plot-container {
            margin: 2rem 0;
            text-align: center;
        }
        .plot-container img {
            max-width: 100%;
            border-radius: 8px;
            border: 1px solid var(--border);
            box-shadow: 0 2px 4px rgba(0,0,0,0.05);
        }
        .markdown-content {
            margin-top: 2rem;
        }
        table {
            border-collapse: collapse;
            width: 100%;
            margin: 1.5rem 0;
        }
        th, td {
            border: 1px solid var(--border);
            padding: 12px;
            text-align: left;
        }
        th { background-color: var(--bg); }
    </style>
</head>
<body>
    <div class="container">
        <div class="header">
            <h1>AStats: Statistical Analysis Report</h1>
            <div class="meta-info">
                <span><strong>Dataset:</strong> {dataset_name}</span>
                <span><strong>Generated:</strong> {timestamp}</span>
            </div>
        </div>

        <div class="query-box">
            <h3>Research Question</h3>
            <p><em>"{query}"</em></p>
        </div>

        <div class="markdown-content">
            <h2>Statistical Findings</h2>
            <div>{final_answer}</div>
        </div>

        {plot_section}

        <hr style="margin: 3rem 0; border: none; border-top: 1px solid var(--border);">
        <div style="font-size: 0.8em; color: #888; text-align: center;">
            <p>Generated by AStats Gen-3 Architecture<br>
            <em>Zero-dependency report: all graphics are Base64 encoded.</em></p>
        </div>
    </div>
</body>
</html>
"""

def _image_to_base64(filepath: str) -> str:
    """Converts a local image file to a base64 string for HTML embedding."""
    try:
        with open(filepath, "rb") as f:
            encoded_string = base64.b64encode(f.read()).decode('utf-8')
        # Infer mime type from extension
        ext = filepath.split('.')[-1].lower()
        mime_type = "image/png"
        if ext in ["jpg", "jpeg"]: mime_type = "image/jpeg"
        elif ext == "svg": mime_type = "image/svg+xml"
        return f"data:{mime_type};base64,{encoded_string}"
    except Exception as e:
        return ""


def generate_html_report(
    query: str, 
    dataset_name: str, 
    final_answer: str, 
    plot_path: str | None = None,
    output_filename: str = "astats_report.html"
) -> str:
    """
    Generates a standalone HTML report with embedded Base64 graphics.
    Returns the absolute path to the generated HTML file.
    """
    import markdown
    
    # Convert LLM markdown output to HTML
    try:
        html_answer = markdown.markdown(final_answer, extensions=['tables'])
    except ImportError:
        # Fallback if markdown package not installed
        html_answer = final_answer.replace('\\n', '<br>')

    plot_section = ""
    if plot_path and os.path.exists(plot_path):
        b64_img = _image_to_base64(plot_path)
        if b64_img:
            plot_section = f'''
            <div class="plot-container">
                <h2>Visual Analytics</h2>
                <img src="{b64_img}" alt="Generated Plot">
            </div>
            '''

    timestamp = datetime.now().strftime("%Y-%m-%d %H:%M:%S")

    html_content = HTML_TEMPLATE.format(
        dataset_name=os.path.basename(dataset_name),
        timestamp=timestamp,
        query=query,
        final_answer=html_answer,
        plot_section=plot_section
    )

    with open(output_filename, "w", encoding="utf-8") as f:
        f.write(html_content)

    return os.path.abspath(output_filename)
